// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqTAIeoaO-6IDIvd_UNHfrN_fwauYXR_Y',
    appId: '1:452726413652:web:3143107b3946bf5a3810c1',
    messagingSenderId: '452726413652',
    projectId: 'auth-e034a',
    authDomain: 'auth-e034a.firebaseapp.com',
    storageBucket: 'auth-e034a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESKHN47qxnEjGR5CVXO85HPEszylunjE',
    appId: '1:452726413652:android:ad28082af1b534e93810c1',
    messagingSenderId: '452726413652',
    projectId: 'auth-e034a',
    storageBucket: 'auth-e034a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqTAIeoaO-6IDIvd_UNHfrN_fwauYXR_Y',
    appId: '1:452726413652:web:8675a69d8deaed503810c1',
    messagingSenderId: '452726413652',
    projectId: 'auth-e034a',
    authDomain: 'auth-e034a.firebaseapp.com',
    storageBucket: 'auth-e034a.appspot.com',
  );
}
